### ISSUE TITLE
请教部署完后点击 业务集列表 出错

### ISSUE THREAD

**Issue by chenshugang** [Tencent/TSeer#17]
报错：
拉取业务集列表失败，错误原因：调用callSeerInterface失败,result = null,interface_name=getservicegroup
如何处理 ？ 谢谢

**Comment by troycheng** [comment]
检查一下TseerServer有没有启动成功，以及resin项目配置里涉及 TseerServer 的ip端口有没有配置正确

**Comment by chenshugang** [comment]
ok 3ks
